name: Build Android Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    env:
      ARCH: arm64
      SUBARCH: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            bc \
            bison \
            build-essential \
            ca-certificates \
            ccache \
            curl \
            flex \
            git \
            libelf-dev \
            libncurses5-dev \
            libssl-dev \
            lzop \
            python \
            python-dev \
            unzip \
            wget \
            xz-utils \
            zip

      - name: Clone toolchains
        run: |
          mkdir toolchain
          git clone https://github.com/0xwhitehatdev/toolchain_4_9_aarch64.git toolchain

      - name: Setup toolchain
        run: |
           TC="$GITHUB_WORKSPACE/toolchain/gcc-cfp/gcc-ibv-jopp"

           echo "$TC/aarch64-linux-android-4.9/bin" >> "$GITHUB_PATH"

           echo "ARCH=arm64" >> $GITHUB_ENV
           echo "CROSS_COMPILE=$TC/aarch64-linux-android-4.9/bin/aarch64-linux-android-" >> $GITHUB_ENV
           

      - name: Build
        run: |
          echo "ANDROID_MAJOR_VERSION=q" >> $GITHUB_ENV
          make ARCH=arm64 exynos9810-crownlte_defconfig 

          make -j$(nproc) \
            ARCH=arm64 \
            CROSS_COMPILE=$CROSS_COMPILE 

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: |
            arch/arm64/boot/Image*
            arch/arm64/boot/dtb*
            arch/arm64/boot/dts/**/*.dtb
