name: Patch Boot Image

on:
  workflow_run:
    workflows: ["Build Android Kernel"]
    types:
      - completed

permissions:
  contents: read

jobs:
  patch:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: Download latest successful kernel artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: main.yml          # <-- your build workflow filename
          workflow_conclusion: success
          name: kernel                 # <-- artifact name from build workflow
          path: artifact

      - name: Verify artifact
        run: |
          ls -lah artifact

      - name: Extract artifact (if zipped)
        run: |
          mkdir out/kernel -p

          FILE=$(find artifact -maxdepth 1 -type f | head -1)

          case "$FILE" in
            *.zip)
              unzip -o "$FILE" -d out/kernel
              ;;
            *.tar.gz|*.tgz)
              tar -xzf "$FILE" -C out/kernel
              ;;
            *)
              cp -r artifact/* out/kernel/
              ;;
          esac


      - name: Clone Local Kitchen 
        run: |
             git clone --depth=1 https://github.com/0xwhitehatdev/Kitchen.git

      - name: Clone mktool
        run: |
          git clone --depth=1 https://github.com/GameTheory-/mktool.git

      - name: Make backend tools executable
        run: |
          chmod +x mktool/tools/*
          ls -lah mktool/tools

      - name: Unpack boot.img
        run: |
          mkdir unpack

          ./mktool/tools/unpackbootimg \
            -i Kitchen/boot.img \
            -o unpack

      - name: Replace kernel
        run: |
          cp out/kernel/Image unpack/boot.img-kernel

      - name: Repack boot.img
        run: |
          CMDLINE=$(cat unpack/boot.img-cmdline)
          BASE=$(cat unpack/boot.img-base)
          PAGESIZE=$(cat unpack/boot.img-pagesize)
          KOFF=$(cat unpack/boot.img-kernel_offset)
          ROFF=$(cat unpack/boot.img-ramdisk_offset)
          SOFF=$(cat unpack/boot.img-second_offset)
          TOFF=$(cat unpack/boot.img-tags_offset)
          HASH=$(cat unpack/boot.img-hash)

          DT=""

          if [ -f unpack/boot.img-dt ]; then
            DT="--dt unpack/boot.img-dt"
          fi

          ./mktool/tools/mkbootimg \
            --kernel unpack/boot.img-zImage \
            --ramdisk unpack/boot.img-ramdisk.gz \
            --cmdline "$CMDLINE" \
            --base "$BASE" \
            --pagesize "$PAGESIZE" \
            --kernel_offset "$KOFF" \
            --ramdisk_offset "$ROFF" \
            --second_offset "$SOFF" \
            --tags_offset "$TOFF" \
            --hash "$HASH" \
            $DT \
            -o boot-new.img

      - uses: actions/upload-artifact@v4
        with:
          name: boot-new
          path: boot-new.img
